[package]
name = "bailong_core"
version = "0.1.0"
authors = ["enter <enterindex@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustpython-parser = "0.1.2"
pyo3 = "0.13.2"
lazy_static = "1.4.0"